import { randomBytes } from 'node:crypto'

export const docs = {
  onlyId: { id: randomBytes(32).toString('hex') },
  badDocType: {
    id: randomBytes(32).toString('hex'),
    schemaType: 'doesnotexist',
    links: [],
    createdAt: new Date().toJSON(),
    refs: [],
    attachments: [],
    metadata: {
      manual_location: true,
    },
  },
  badSchemaVersion: {
    id: randomBytes(32).toString('hex'),
    schemaType: 'observation',
    schemaVersion: 2,
    links: [],
    createdAt: new Date().toJSON(),
    refs: [],
    attachments: [],
    metadata: {
      manual_location: true,
    },
  },
  good: {
    observation_5: {
      id: randomBytes(32).toString('hex'),
      schemaType: 'observation',
      createdAt: new Date().toJSON(),
      updatedAt: new Date().toJSON(),
      links: [],
    },
    preset: {
      id: randomBytes(32).toString('hex'),
      createdAt: new Date().toJSON(),
      updatedAt: new Date().toJSON(),
      schemaType: 'preset',
      links: [],
      tags: { nature: 'tree' },
      geometry: ['point'],
      name: 'john',
    },
    field: {
      id: randomBytes(32).toString('hex'),
      createdAt: new Date().toJSON(),
      updatedAt: new Date().toJSON(),
      schemaType: 'field',
      tagKey: 'hi',
      type: 'text',
      links: [],
    },
    coreOwnership: {
      schemaType: 'coreOwnership',
      id: randomBytes(32).toString('hex'),
      coreId: randomBytes(32).toString('hex'),
      projectId: randomBytes(32).toString('hex'),
      storeType: 'blob',
      authorIndex: 10,
      deviceIndex: 10,
      action: 'core:owner',
      createdAt: new Date().toJSON(),
      updatedAt: new Date().toJSON(),
      links: [],
    },
    device: {
      schemaType: 'device',
      id: randomBytes(32).toString('hex'),
      action: 'device:add',
      authorId: randomBytes(32).toString('hex'),
      projectId: randomBytes(32).toString('hex'),
      signature: 'hi',
      authorIndex: 10,
      deviceIndex: 10,
      createdAt: new Date().toJSON(),
      updatedAt: new Date().toJSON(),
      links: [],
    },
    role: {
      id: randomBytes(32).toString('hex'),
      schemaType: 'role',
      role: 'project-creator',
      projectId: randomBytes(32).toString('hex'),
      action: 'role:set',
      signature: 'hi',
      authorIndex: 10,
      deviceIndex: 10,
      createdAt: new Date().toJSON(),
      updatedAt: new Date().toJSON(),
      links: [],
    },
  },
}
