name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version:
          - '16.x'
          - '18.x'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install buf cli
        uses: bufbuild/buf-setup-action@v1.9.0
      - run: buf --version
        uses: actions/cache@v3
      - name: get buf hash
        id: buf-hash
        run: |
          echo "bufHash=$(shasum $(which buf) | awk '{print $1}')" >> $GITHUB_OUTPUT
      - name: Cache buf binary
        with:
          path: /opt/hostedcachetool/buf/1.9.0/x64/bin/
          key: ${{ steps.buf-hash.outputs.bufHash }}
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: false
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
